# Generated by bun2nix
# Run 'bun2nix -o bun.nix' to regenerate this file

{
  pname = "docs";
  version = "0.0.1";
  
  # This will be populated by bun2nix after running the postinstall script
  # For now, this is a placeholder that will be overwritten
  
  meta = {
    description = "Dependencies for play.ts documentation site";
  };
}