# Generated by bun2nix
# This is a minimal placeholder - will be replaced by actual bun2nix output

{
  pname = "docs";
  version = "0.0.1";
  
  bunNix = {
    deps = [
      # Dependencies will be populated by bun2nix
    ];
  };
  
  meta = {
    description = "Dependencies for play.ts documentation site";
  };
}